### ISSUE TITLE
When using multiple auth providers, BasicAuthentication is fired first

### ISSUE THREAD

**Issue by DenisBalan** [webmotions/fake-authentication-jwtbearer#12]
In our project we have
```
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApi(Configuration, "AzureAD");
            services.AddAuthentication("BasicAuthentication")
                .AddScheme<AuthenticationSchemeOptions, BasicAuthenticationHandler>("BasicAuthentication", null);
```

Therefor when writing tests, and adding
```
using var host = Host.CreateDefaultBuilder()
     .ConfigureWebHostDefaults(builder =>
     {
         builder
        .UseTestLogging()
        .UseTestServer()
        .ConfigureTestServices(services =>
        {
            services.AddAuthentication(FakeJwtBearerDefaults.AuthenticationScheme).AddFakeJwtBearer();

        })
.UseStartup<Startup>();
```

So by default its throwing error, becuase inside `AuthenticationOptions DefaultAuthenticateScheme` is set to BasicAuthentication.

quick fix:
```
using var host = Host.CreateDefaultBuilder()
     .ConfigureWebHostDefaults(builder =>
     {
         builder
        .UseTestLogging()
        .UseTestServer()
        .ConfigureTestServices(services =>
        {

            services.AddAuthenticationCore(x => x.DefaultAuthenticateScheme = FakeJwtBearerDefaults.AuthenticationScheme);
            services.AddAuthentication(FakeJwtBearerDefaults.AuthenticationScheme).AddFakeJwtBearer();

        })
.UseStartup<Startup>();
```

**Comment by DOMZE** [comment]
Since you're calling multiple times `services.AddAuthentication()` you're redefining the defaultScheme every time you are calling it. In my test, ConfigureTestServices is called last and thus is the last one that prevails, as stated in the doc:

For SUTs that still use the [Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-6.0), the test app's builder.ConfigureServices callback is executed before the SUT's Startup.ConfigureServices code. The test app's builder.ConfigureTestServices callback is executed after.

see [this](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0)

Do you want to both use BasicAuth AND FakeBearer in your tests? If so you may need to review how you setup your stuff.
